spring.application.name: build-the-guild

logging:
  file:
    name: BuildTheGuild-backend.log
  logback:
    rollingpolicy:
      max-history: 5
      max-file-size: 10MB

buildtheguild:
  security:
    jwt-secret: ${BTG_JWT_SECRET:btgJwtSecret}
    jwt-expiration: 172800000

server:
  servlet:
    context-path: /api

spring:
  boot:
    admin.client:
      url: http://localhost:8084
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${BTG_DATASOURCE_URL:jdbc:postgresql://localhost:5432/build_the_guild}
    username: ${BTG_DATASOURCE_USERNAME:USER_BTG}
    password: ${BTG_DATASOURCE_PASSWORD:USER_BTG1}
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: create-drop

management:
  endpoints:
    web.exposure:
      include: "health,logfile,info"
  endpoint:
    health.show-details: always